import createClient from 'openapi-fetch'
import type { paths } from './schema' // generated by openapi-typescript

/**
 * Example usage:
 * ```
 *   const {data, error, response} = await client.GET("/isbn/{isbn}.json", {
 *     params: { path: { isbn: "1234567890" } }
 *   })
 * ```
 */
export const client = createClient<paths>({ baseUrl: 'https://openlibrary.org/' })
